/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mybank;

import com.mybank.atm.Atm;

public class App {

    public static void main(String[] args) {
        // Give a default bank name and database name when required
        String bankName = args.length < 1 ? "MyBank" : args[0];
        String databaseName = args.length < 2 ? "mybank.db" : args[1];

        // "jdbc:sqlite:app/database/"
        Atm atm = new Atm(bankName, "jdbc:sqlite:" + databaseName);
        atm.start();
    }

    // ignore this method ; called in test module for com.mybank.AppTest under test sources root
    public String getGreeting() {
        return "Greetings ";
    }
}
